FROM openjdk:11

# Instalación de utilidades necesarias
RUN apt-get update && \
    apt-get install -y wget tar ssh net-tools procps dos2unix && \
    ssh-keygen -A && \
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config && \
    echo "root:root" | chpasswd

# Variables de entorno
ENV HADOOP_VERSION=2.7.3
ENV PIG_VERSION=0.17.0

ENV HADOOP_HOME=/opt/hadoop
ENV PIG_HOME=/opt/pig
ENV JAVA_HOME=/usr/local/openjdk-11
ENV PATH="$JAVA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$PIG_HOME/bin:$PATH"
ENV HADOOP_CONF_DIR=$HADOOP_HOME/etc/hadoop

# Instalar Hadoop desde archivo archivado
RUN wget https://archive.apache.org/dist/hadoop/common/hadoop-$HADOOP_VERSION/hadoop-$HADOOP_VERSION.tar.gz && \
    tar -xzf hadoop-$HADOOP_VERSION.tar.gz && \
    mv hadoop-$HADOOP_VERSION $HADOOP_HOME && \
    rm hadoop-$HADOOP_VERSION.tar.gz

# Instalar Pig desde archivo archivado
RUN wget https://archive.apache.org/dist/pig/pig-$PIG_VERSION/pig-$PIG_VERSION.tar.gz && \
    tar -xzf pig-$PIG_VERSION.tar.gz && \
    mv pig-$PIG_VERSION $PIG_HOME && \
    rm pig-$PIG_VERSION.tar.gz && \
    chmod +x $PIG_HOME/bin/pig

# Crear carpetas de trabajo
RUN mkdir -p /pig/input /pig/output /workspace/resultados

# Copiar scripts y datos
COPY scripts /pig/scripts
COPY data /pig/data

# Convertir a formato Unix los scripts para evitar errores de \r\n
RUN dos2unix /pig/scripts/*.sh

# Copiar configuraciones personalizadas de Hadoop si tienes


# Definir carpeta de trabajo
WORKDIR /workspace

# Exponer puertos necesarios
EXPOSE 22 9870 8088

# Comando por defecto al arrancar el contenedor
CMD ["bash", "/pig/scripts/start.sh"]
