FROM python:3.10-slim

WORKDIR /app
COPY eventos_waze.json .
COPY requirements.txt .

# Install system dependencies and build tools
RUN apt-get update && \
    apt-get install -y libpq-dev gcc python3-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get purge -y --auto-remove gcc python3-dev libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY main.py .

CMD [ "python", "-u", "main.py" ]
