FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    wget \
    ca-certificates \
    tcl \
    && rm -rf /var/lib/apt/lists/*

ENV REDIS_VERSION=7.2.4

RUN wget http://download.redis.io/releases/redis-${REDIS_VERSION}.tar.gz && \
    tar xzf redis-${REDIS_VERSION}.tar.gz && \
    cd redis-${REDIS_VERSION} && \
    make && make install && \
    cd .. && rm -rf redis-${REDIS_VERSION}*

COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["redis-server"]
EXPOSE 6379
